CREATE TABLE IF NOT EXISTS "Artikel" (
                                         "ArtikelID" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                         "ArtikelTyp" TEXT NOT NULL,
                                         PRIMARY KEY("ArtikelID")
    );

CREATE TABLE IF NOT EXISTS "Mitarbeiter" (
                                             "MitarbeiterID" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                             PRIMARY KEY("MitarbeiterID")
    );

CREATE TABLE IF NOT EXISTS "Ausleihe" (
                                          "ArtikelID" INTEGER NOT NULL,
                                          "MitarbeiterID" INTEGER NOT NULL,
                                          "Ausleihdatum" DATE NOT NULL,
                                          "Abgabedatum" DATE,
                                          PRIMARY KEY("ArtikelID", "MitarbeiterID")
    ) INHERITS ("Artikel", "Mitarbeiter");

ALTER TABLE "Artikel"
    ADD FOREIGN KEY("ArtikelID") REFERENCES "Ausleihe"("ArtikelID")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Mitarbeiter"
    ADD FOREIGN KEY("MitarbeiterID") REFERENCES "Ausleihe"("MitarbeiterID")
        ON UPDATE NO ACTION ON DELETE NO ACTION;